service: daily-scraper
frameworkVersion: "4"

provider:
  name: aws
  region: us-east-2
  ecr:
    images:
      scraper-image:
        uri: 849681699653.dkr.ecr.us-east-2.amazonaws.com/web-scanner:latest

functions:
  runScraper:
    image: scraper-image
    timeout: 300 # 5 minutes, adjust as needed
    memorySize: 1024 # Recommended for Playwright
    events:
      - schedule: rate(1 day) # Execute daily

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!*.md"
    - "!.git/**"
