service: daily-scraper
frameworkVersion: "4"

provider:
  name: aws
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - ecr:BatchCheckLayerAvailability
          Resource:
            - "arn:aws:ecr:us-east-2:849681699653:repository/daily-scraper-web-scraper"

functions:
  runScraper:
    image:
      uri: 849681699653.dkr.ecr.us-east-2.amazonaws.com/daily-scraper-web-scraper:v1.55.0
    timeout: 300
    memorySize: 1024
    environment:
      BOTLINE_ENDPOINT: ${env:BOTLINE_ENDPOINT}
      BOTLINE_TOKEN: ${env:BOTLINE_TOKEN}
      NODE_ENV: production
    events:
      - schedule: rate(1 day)
## Note: serverless-offline removed — local dev uses Docker image and HTTP invocation
