service: daily-scraper
frameworkVersion: "4"

provider:
  name: aws
  region: us-east-2 # You can change this if needed
  runtime: nodejs18.x

functions:
  runScraper:
    handler: dist/index.handler
    timeout: 300 # 5 minutes, adjust as needed
    memorySize: 1024 # Recommended for Playwright
    events:
      - schedule: rate(1 day) # Execute daily

plugins:
  - serverless-offline # Useful for local development with non-dockerized functions

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!*.md"
    - "!.git/**"
