service: daily-scraper
frameworkVersion: "4"

provider:
  name: aws
  region: us-east-2 # You can change this if needed
  ecr:
    images:
      scraper-image:
        path: . # Path to your Dockerfile

functions:
  runScraper:
    image:
      name: scraper-image
    timeout: 300 # 5 minutes, adjust as needed
    memorySize: 1024 # Recommended for Playwright
    events:
      - schedule: rate(1 day) # Execute daily

plugins:
  - serverless-offline # Useful for local development with non-dockerized functions

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!*.md"
    - "!.git/**"
